defaults:
  - datas: edge2shoes
  - model: defaults_vae
  - paths: defaults
  - metrics: defaults

experiment_name : SIVAE_experiment_Gen_${model.names.netG_name}_WhereAdd_${model.names.where_add_type}_Discrim_${model.names.netD_name}
experiment_path : runs/${experiment_name}

params:
  batch_size : 1
  num_epochs : 10
  num_styles: 10 # Number of styles to sample
  num_images : 8  # Number of images to test