encoder:
  _target_: torch.optim.lr_scheduler.MultiStepLR
  _partial_: true
  milestones: [37, 45]
  gamma: 0.1
decoder:
  _target_: torch.optim.lr_scheduler.MultiStepLR
  _partial_: true
  milestones: [37, 45]
  gamma: 0.1